import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Eye, EyeOff, Lock } from "lucide-react";
import { LanguageSwitcher } from "@/components/LanguageSwitcher";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import { toast } from "sonner";

/**
 * Page shown to employees after they click the invite link sent via email.
 *
 * The link generated by the invite‑employee edge function logs the user in
 * and redirects them here. On this page the employee can set their own
 * password. After successfully setting the password the corresponding
 * invitation record is updated to `accepted` and the user is taken to
 * their dashboard. If anything goes wrong a toast message is shown.
 */
const EmployeeInvite = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(true);
  const [updating, setUpdating] = useState(false);
  const [userEmail, setUserEmail] = useState<string | null>(null);
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  // Track whether we have performed an initial sign‑out.  When this page
  // loads there may be an existing session (e.g. when an admin clicks
  // their invite link while logged in).  Updating a password while the
  // wrong user is logged in would change the wrong account.  To prevent
  // this, we sign out once on mount so that the magic invite token can
  // establish a new session.  Without this the user must manually log
  // out before clicking the invite link【352934996388639†L276-L283】.
  const [signedOutOnce, setSignedOutOnce] = useState(false);

  // On mount fetch the current authenticated user. The invite link created
  // by Supabase automatically signs the user in so there should be a
  // session available. We capture the email to update the corresponding
  // invitation record.
  // On mount sign out any existing session to ensure the invite link
  // establishes the correct session.  We only do this once to avoid
  // infinite loops.  After signing out, Supabase will see the token in
  // the URL hash and automatically set a new session for the invited
  // user.  See Supabase docs on invites for more details【352934996388639†L276-L283】.
  useEffect(() => {
    const prepareSession = async () => {
      if (!signedOutOnce) {
        await supabase.auth.signOut();
        setSignedOutOnce(true);
      }
      const { data, error } = await supabase.auth.getUser();
      if (error) {
        console.error(error);
        toast.error(error.message);
        setLoading(false);
        return;
      }
      setUserEmail(data.user?.email ?? null);
      setLoading(false);
    };
    prepareSession();
  }, [signedOutOnce]);

  // Handle form submission. Ensures both passwords match, updates the
  // authenticated user's password and marks the invitation as accepted.
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (updating) return;

    if (password !== confirmPassword) {
      toast.error(t("auth.passwordsDoNotMatch", { defaultValue: "Die Passwörter stimmen nicht überein." }));
      return;
    }

    if (!userEmail) {
      toast.error(t("auth.noInviteUser", { defaultValue: "Kein eingeladener Benutzer gefunden." }));
      return;
    }

    setUpdating(true);
    // Update the user's password via Supabase Auth. This will invalidate the
    // invite token and allow the user to log in normally.
    const { error: updateError } = await supabase.auth.updateUser({ password });
    if (updateError) {
      toast.error(updateError.message);
      setUpdating(false);
      return;
    }

    // Update any outstanding invitations for this email to accepted. We
    // intentionally update all pending or sent invitations to avoid leaving
    // stale records.
    await supabase
      .from("employee_invitations")
      .update({ status: "accepted" })
      .in("status", ["pending", "sent"])
      .eq("email", userEmail);

    toast.success(t("auth.passwordUpdated", { defaultValue: "Passwort erfolgreich gespeichert." }));
    setUpdating(false);
    // Redirect the user to the employee dashboard. If your app uses a
    // different landing page for invited users adjust this path accordingly.
    navigate("/employee-dashboard");
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <p className="text-muted-foreground">{t("common.loading", { defaultValue: "Lädt…" })}</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background flex">
      {/* Left Side - Form */}
      <div className="flex-1 flex flex-col">
        {/* Header with Theme/Language Switchers */}
        <div className="flex justify-end p-4 gap-2">
          <LanguageSwitcher />
          <ThemeSwitcher />
        </div>

        <div className="flex-1 flex items-center justify-center p-8">
          <div className="w-full max-w-md space-y-8 animate-fade-in">
            <div className="text-center">
              <h1 className="text-3xl font-display font-bold text-foreground mb-2">
                {t("auth.setPasswordTitle", { defaultValue: "Passwort festlegen" })}
              </h1>
              <p className="text-muted-foreground">
                {t("auth.setPasswordSubtitle", { defaultValue: "Bitte legen Sie Ihr neues Passwort fest." })}
              </p>
            </div>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="space-y-2">
                <Label htmlFor="password">{t("auth.newPassword", { defaultValue: "Neues Passwort" })}</Label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                  <Input
                    id="password"
                    type={showPassword ? "text" : "password"}
                    placeholder="••••••••"
                    className="pl-10 pr-10"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                    minLength={8}
                  />
                  <button
                    type="button"
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
                    onClick={() => setShowPassword(!showPassword)}
                  >
                    {showPassword ? <EyeOff className="w-5 h-5" /> : <Eye className="w-5 h-5" />}
                  </button>
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="confirmPassword">{t("auth.confirmPassword", { defaultValue: "Passwort bestätigen" })}</Label>
                <div className="relative">
                  <Lock className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground" />
                  <Input
                    id="confirmPassword"
                    type={showPassword ? "text" : "password"}
                    placeholder="••••••••"
                    className="pl-10 pr-10"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    required
                    minLength={8}
                  />
                </div>
              </div>
              <Button type="submit" variant="hero" className="w-full" size="lg" disabled={updating}>
                {updating ? t("common.loading", { defaultValue: "Lädt…" }) : t("auth.savePassword", { defaultValue: "Passwort speichern" })}
              </Button>
            </form>
          </div>
        </div>
      </div>
      {/* Optional right side pattern for larger screens to match existing auth pages */}
      <div className="hidden lg:flex flex-1 gradient-primary relative overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-20 right-20 w-72 h-72 border border-primary-foreground rounded-full" />
          <div className="absolute bottom-20 left-20 w-96 h-96 border border-primary-foreground rounded-full" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-64 h-64 border border-primary-foreground rounded-full" />
        </div>
        <div className="flex items-center justify-center w-full">
          <div className="text-center text-primary-foreground p-12">
            <h2 className="text-4xl font-display font-bold mb-4">
              {t("landing.cta.badge", { defaultValue: "Willkommen" })}
            </h2>
            <p className="text-xl opacity-80 max-w-md">
              {t("landing.cta.subtitle", { defaultValue: "Starten Sie mit Ihrer neuen Rolle." })}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default EmployeeInvite;